### ISSUE TITLE
eraser-selection no longer works (and can erase entire page) after 3.7.0.1930 update

### ISSUE THREAD

**Issue by javalasers** [slotThe/RemarkableLamyEraser#1]
I have "click" bound to "eraser-selection". After the 3.7.0.1930 update, if the "Eraser" is currently visible in the toolbar and I click, then "Eraser" gets selected, but nothing else happens.

However, if "Selection eraser" is already visible in the toolbar and I click, then all the writing on the page is immediately erased (as if I had opened up the eraser panel and clicked "Erase all").

I suspect something changed in the UI for this update or another recent update, and the "eraser-selection" action is now blindly clicking in the wrong place(?)

**Comment by slotThe** [comment]
> I suspect something changed in the UI for this update or another recent update, and the "eraser-selection" action is now blindly clicking in the wrong place(?)

I would imagine so, yes. I'll update to 3.7.x soon and report back whether I can reproduce this on that version.

**Comment by slotThe** [comment]
Just popping back in here to say that I haven't forgotten about this, but my reMarkable doesn't seem to know of the existence of a version 3.7.x. Let's see how long that takes to trickle down :)

**Comment by slotThe** [comment]
Well, this is a bit awkward :/

The point seems to be that the touch requests are occurring too frequently and the reMarkable is getting confused. Of course, one could fix this by introducing some delay between certain presses, but that results in a noticable "flicker" of the toolbar… I really just wish we had an API to work with. Oh well.
