### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by Gfernandez91** [slotThe/RemarkableLamyEraser#24]
Hello, the link seems to be dead when installing the hack via terminal. Not sure if it is user error or an issue with the data.

**Comment by slotThe** [comment]
I've tried this a few times now and I can't reproduce this; are you sure that your reMarkable has internet access?

**Comment by Gfernandez91** [comment]
> I've tried this a few times now and I can't reproduce this; are you sure that your reMarkable has internet access?

Wow! I didn't realize that wifi needed to be on in the device. Sorry! Thank you for pointing out this fix. I was hardwired and thought it was pulling the data from my computer.
