### ISSUE TITLE
Trying to bind click -> erase select just produces errors and does not work on-tablet!

### ISSUE THREAD

**Issue by CoolPenguin42** [slotThe/RemarkableLamyEraser#25]
![Screenshot 2024-09-14 191344](https://github.com/user-attachments/assets/91162965-a687-4e83-ae40-ff55691fbb9c)

Basically I unbound all the other commands, just made it so that click = changing to eraser select tool. However, upon trying this on the tablet nothing actually happened. So i opened up that thing that shows the log of the tablet screen connections, and inspected what was happening. As you can see, it seems to try and access a file and just completely dies lol. Is this something that needs to be fixed on my end? Did i mess something up? I am on version 3.11.2.5 remarkable 2, with 0.0.10 rM hacks.

**Comment by slotThe** [comment]
That first error looks like the locale on the reMarkable doesn't like some of those symbols
