### ISSUE TITLE
no certificate error

### ISSUE THREAD

**Issue by BPWZHJCZ** [slotThe/RemarkableLamyEraser#4]
I'm getting a no certificate error when I try to install on 3.7. It's not an SSH error, it's a no certificate warning and then the install fails. Is this common or known issue?

**Comment by slotThe** [comment]
I can't reproduce this; would you mind posting the exact error you're getting?

**Comment by BPWZHJCZ** [comment]
Connecting to [github.com](http://github.com/) ([20.248.137.48:443](http://20.248.137.48:443/))
wget: TLS error from peer (alert code 80): 80
wget: error getting response: Connection reset by peer

**Comment by slotThe** [comment]
I can't reproduce this; are you sure that you have an internet connection on your reMarkable?

**Comment by moondigital** [comment]
I am getting the same error on 3.7.0.1930.

**Comment by ThomasNobesMonash** [comment]
I also encounter the same error. Seems to be an issue with `busybox:musl` [thread](https://github.com/GoogleContainerTools/kaniko/issues/2452 )

**Comment by slotThe** [comment]
Since I'm not running into this I'm having a hard time believing it's a bug in busybox—presumably, everyone on 3.7.0.1930 gets the same version of it?

Anyways, the only thing I can think of is a redirect causing troubles. I'll try to investigate further.

**Comment by slotThe** [comment]
I twiddled about with the URLs in https://github.com/slotThe/RemarkableLamyEraser/commit/c5c2f60cdeaeb5ff31771ac1827922f140ea83a3; can anyone notice any difference? :)

**Comment by moondigital** [comment]
Perfect! Thank you for your work on this project.
