### ISSUE TITLE
Configuration for `toggle` (ideally without menu flickering)

### ISSUE THREAD

**Issue by zeyutang** [slotThe/RemarkableLamyEraser#6]
Hi, I am wondering how can I set up a toggle for certain actions with the same trigger.

For example, use `click` to switch between the writing tool (with previous setup for the pen, either writing or highlighting) and the erasing tool (previously used eraser, e.g., erase the lasso selected area, i.e., the `eraser-selection`).

An example configuration that does not work (RM2 v3.7.0.1930):
```text
# Everything else remains unchanged in configuration
click                    eraser-panel,writing
double-click             undo
```

The ideal situation would be to just toggle between the tools without flickering the menu bar (which was touched on in #1).

I haven't find a related instruction in [issacwisdom's repo](https://github.com/isaacwisdom/RemarkableLamyEraser), since the configuration there is in terms of flags (e.g., `--toggle` mode), please just let me know if there is already one (in this repo or somewhere else).

Thanks!

**Comment by slotThe** [comment]
There is not API to speak of for doing this, so we'd need to find a way to query the currently selected item from the toolbar. I haven't found anything yet, so this is not possible right now
