### ISSUE TITLE
Click actions

### ISSUE THREAD

**Issue by somedaygone** [slotThe/RemarkableLamyEraser#7]
I'm trying to get all the click actions working, and I'm struggling. On occasion I can get the click action to work, but it usually takes me five tries. Near as I can tell, you have to click really fast for it to work and I just can't pull it off while holding the pen. Even more rare is the time I can make a double click work, and I've never done a triple click. Can you confirm the speed that is needed by default, and whether the speed can be adjusted?

Also on occasion I do something that causes the toolbar menu to close. Any idea of what that is?

Thanks! I'm using a Kindle Scribe and Samsung S pen on rM2 version 3.8, and the press and hold to erase works great (80-90%) with the Kindle pen but a little flaky (50-60%) with the Samsung pen (on 3.7 too).
![image](https://github.com/slotThe/RemarkableLamyEraser/assets/4382563/e1edd7eb-aeb9-488c-b90d-7943615f7bd7)

**Comment by somedaygone** [comment]
Nevermind. I figured out today it's all about the distance to the screen, not the speed of the clicks. If I'm holding the pen like I'm poised to begin writing real close to the screen, it works perfect every time.

**Comment by slotThe** [comment]
Yes, distance to the screen is important. Otherwise, the pen isn't sending any signal to the EMR screen. I've been using tripple clicks [+ hold] myself without too many problems
