### ISSUE TITLE
Double and triple click support in Version 3.9.3.1986

### ISSUE THREAD

**Issue by raju-bitter** [slotThe/RemarkableLamyEraser#9]
I installed the software on a reMarkable 2 device with software version 3.9.3.1986. Using the button click and hold to erase content works fine with the Lamy pen. But double click undo or triple click redo does not work.

Is that the expected behavior at the moment?

**Comment by slotThe** [comment]
I'm still on 3.8.x, so I can't say for sure. Unless the UI changed (did it?), however, things should generally continue to work smoothly

**Comment by raju-bitter** [comment]
The first problem was that the tip of my pen was not close enough to the surface of the device when doing undo/redo, easy to fix. But there is something strange going on with the toolbar. When the toolbar is hidden undo/redo using double and triple click works fine. But when the toolbar is visible, I can only undo/redo one time. The toolbar will hide after the first action, I can still draw and use the button hold to erase. But the double/triple click don't do any action, although the RemarkableLamyEraser program still detects the action.
Once the toolbar hides as a result of the doing undo/redo, the toolbar icon cannot be used any more to show the toolbar, again. But when turning the device off and on, everything is back to normal.

Steps to reproduce the problem:

1. Stop the _LamyEraser.service_, launch the _RemarkableLamyEraser_ directly
2. Start with an empty page
3. Hide the toolbar
4. Draw three strokes
5. Use undo two times (two strokes disappear, one remains)
6. Trigger two redo actions (three strokes visible now)
7. Show the toolbar
8. Undo: now the toolbar disappears, two strokes visible
9. Try another undo: The _RemarkableLamyEraser_ will show the _writing undo_ output, so the action is detected, but not executed.
10. Tap the toolbar icon: the toolbar remains invisible
11. Put the device into sleep, wake up again
12. Trigger undo action: one stroke disappears, only one left

Below is the console output I see on my device for above steps:
```
reMarkable: ~/ systemctl stop LamyEraser.service
reMarkable: ~/ RemarkableLamyEraser 
RemarkableLamyEraser 2.2.0
----------------------------------
Detected ReMarkable 2, Software Version: 3.x.x.x
Using Devices:
1. device file = /dev/input/event1
   device name = Wacom I2C Digitizer
2. device file = /dev/input/event2
   device name = pt_mt
----------------------------------
Using configuration file at /home/root/.config/LamyEraser/LamyEraser.conf
Line 29: Read trigger <double-click> with effect <undo>
Line 30: Read trigger <triple-click> with effect <redo>
Line 34: Read trigger <press&hold> with effect <eraser-erase>
Line 35: Read trigger <double-press&hold> with effect <select>
----------------------------------
writing undo
writing undo
writing redo
writing redo
writing undo
writing undo
writing undo
```

I tested with the Lamy and the Galaxy Note 6 pen. The Samsung Note 6 pen worked fine.

**Comment by rish987** [comment]
I got the same issue as you, though I can't consistently reproduce it in the way you describe. I think this is an upstream bug (so probably not much we can do). I have found that a solution is to add a delay before the simulating the final toolbar tap -- you can find my fix [here](https://github.com/rish987/RemarkableLamyEraser/tree/6f8199263d5e215ff496fb6b66f050f1d28fdb55).

The downside is that it causes flickering from showing and hiding the toolbar and makes the response time for undo longer -- I guess I can live with this, but perhaps it will be enough to motivate me to downgrade to an older version :P

**Comment by raju-bitter** [comment]
Thanks for looking into this, and for the fix. I just started my journed into using Remarkable 2. The Lamy pen is so comfortable to use, so I'm willing to invest some time to support the more experienced developers working on this tool.

I'll try out your fix tomorrow. And will update this comment then.

**Comment by OMotornyi** [comment]
Hello. I am relieved I found this issue - I juts got my rM2 last week and faced this problem, was worried I did something wrong (or something weird going on with rM2 soft/firmware), but turns out it's something general :)

**Comment by rish987** [comment]
FYI, I have personally decided to downgrade to 3.8.3.1976 (for the time being), and this tool is working much more smoothly now. It's very simple to do, just download [codexctl](https://github.com/Jayy001/codexctl), plug in your Remarkable and run `./codexctl.bin install 3.8.3.1976`.

**Comment by raju-bitter** [comment]
I downgraded as well to 3.8.3.1976, and can confirm that it's working much better. The more I learn about the Remarkable, the more I love it. And the community around it.
That's an easy downgrade using `codexctl`. Thanks for pointing out the tool.
And equally thanks to everyone else working on the tool, providing valuable feedback. That's so much appreciated!

**Comment by Reguuuu** [comment]
Hi, I do not know if you guys are still facing this problem, but a great hack is RM-Hacks. Much better, developers update the hack often unlike the lamy hack and everything works very well. Undo with double click, click and hold for erase and double click and hold for select erase. Works with the lamy pen very well and also works for the newest software update with their newest 0.07 patch :D It is what finally worked for me after trying out various hacks for the newest software. Also other hacks are there not only the lamy hack making the RM more user friendly :))))
Github Link to the hack: https://github.com/mb1986/rm-hacks 
Im glad if I could help anyone :)

**Comment by raju-bitter** [comment]
@Reguuuu Thanks for your comment, I'll try it later this week. Sounds like a good alternative hack!

**Comment by rish987** [comment]
> Hi, I do not know if you guys are still facing this problem, but a great hack is RM-Hacks.

I recently discovered this hack as well! I will try it out soon and report back. It's a shame that it cannot be open-source though. Of course, the ideal scenario would be for them to eventually provide some API so that we can set/retrieve the pen state without having to mess around with faking screen taps (thus allowing for the Lamy pen integration at least to be open source).

But anyways, I think I will introduce #11 and #13 to them and see what their thoughts are (I already don't think I can live without these features).

**Comment by slotThe** [comment]
I just upgraded to 3.9, and sadly can't reproduce this. I reckon a larger delay might help, which is something that's on the roadmap anyhow. For now, modifying the source also works
